# Generated by Django 2.0 on 2019-09-16 07:55

from django.db import migrations

def create_currencies(apps, schema_editor):
    from apps.invoices.models import DEFAULT_CURRENCIES
    print()
    print('Data Migration: Creating Default Currencies...')
    for key, create in DEFAULT_CURRENCIES.items():
        print('\t', key, create())

def delete_default_currencies(apps, schema_editor):
    from apps.invoices.models import DEFAULT_CURRENCIES
    PaymentCurrency = apps.get_model('invoices', 'PaymentCurrency')
    print()
    print('Data Migration: Deleting Default Currencies...')
    for key, create in DEFAULT_CURRENCIES.items():
        print('\t', key, PaymentCurrency.objects.filter(symbol=key).delete())

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_currencies, delete_default_currencies),
    ]
