# Generated by Django 2.0 on 2019-07-08 18:42

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whitelistaddress',
            name='secret',
            field=models.CharField(default=apps.users.models.makeKey, max_length=32),
        ),
        migrations.AlterField(
            model_name='whitelistaddress',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('denied', 'Denied'), ('deactivated', 'Deactivated')], default='pending', max_length=32),
        ),
    ]
